[project]
name = "paraspots"
version = "0.1.0"
description = "App for showing paragliding spots in Norway"
authors = [{ name = "Sebastian Grans", email = "sebastian.grans@zivid.com" }]
requires-python = ">=3.12"
dependencies = [
    "pyserde>=0.31.7",
    "pyside6-addons>=6.11.1",
    "pyside6-essentials>=6.11.1",
]

[project.scripts]
paraspots = "paraspots.main:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pyside6>=6.11.1"]
